package bit;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

import bit.cli.Ui;
import bit.storage.Storage;
import bit.task.Task;
import bit.task.TaskList;
import bit.task.Todo;
import bit.task.Deadline;
import bit.task.Event;

/**
 * Bit is a simple command-line task manager.
 * It supports adding tasks (todo, deadline, event),
 * listing tasks, marking/unmarking tasks as done,
 * deleting tasks, and exiting the program.
 *
 * Tasks are stored using parallel arrays for simplicity.
 */
public class Bit {

    public static final String DATA_FILE_PATH = "./data/bit.txt";
    public static final int MAX_TASKS = 100;
    public static final DateTimeFormatter INPUT_DATE = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    public static final DateTimeFormatter INPUT_DATETIME = DateTimeFormatter.ofPattern("yyyy-MM-dd HHmm");

    // Persistent state for GUI + CLI
    private final Ui ui = new Ui();
    private final Storage storage;
    private final TaskList taskList = new TaskList(MAX_TASKS);

    /**
     * Constructs a Bit instance, initializes storage, and loads tasks from disk.
     */
    public Bit() {
        Path filePath = Paths.get(DATA_FILE_PATH);
        storage = new Storage(filePath);

        int loaded = storage.loadTasks(taskList.getInternalArray());
        taskList.setCount(loaded);
    }

    /**
     * Entry point of the Bit application.
     * Continuously reads user commands and executes them
     * until the user enters "bye".
     *
     * @param args Command line arguments (not used).
     */
    public static void main(String[] args) {
        Bit bot = new Bit();
        bot.ui.showWelcome();

        while (true) {
            String input = bot.ui.readCommand();
            String output = bot.getResponse(input);

            if (!output.isBlank()) {
                System.out.println(output);
            }

            if (input.trim().equalsIgnoreCase("bye")) {
                bot.ui.close();
                break;
            }
        }
    }

    /**
     * Processes a user command and returns the response as a string.
     * This method is used by the GUI (and can also be used by CLI).
     *
     * @param input The command entered by the user
     * @return The response generated by Bit
     */
    public String getResponse(String input) {
        if (input == null || input.trim().isEmpty()) {
            return "";
        }

        String command = input.toLowerCase().trim();

        ui.beginCapture(); // <--- capture EVERYTHING into a String

        if (command.equals("bye")) {
            ui.showBye();
            return ui.endCapture();
        }

        if (command.equals("list")) {
            ui.showMessage(taskList.formatList());
            return ui.endCapture();
        }

        if (command.equals("find")) {
            ui.showMessage(
                    "Looking for something? 🔍\n"
                            + "Tell me the keyword and I'll search your tasks.\n"
                            + "Example: find meeting"
            );
            return ui.endCapture();
        }

        if (command.equals("update")) {
            ui.showMessage(
                    "Want to edit a task? ✏️\n"
                            + "Try: update <task number> <new description>\n"
                            + "Example: update 2 submit final report"
            );
            return ui.endCapture();
        }

        if (command.equals("mark") || command.equals("unmark") || command.equals("delete")) {
            ui.showMessage(
                    "I need a task number 🙂\n"
                            + "Try:\n"
                            + "mark <task number>\n"
                            + "unmark <task number>\n"
                            + "delete <task number>\n"
                            + "Example: mark 2"
            );
            return ui.endCapture();
        }

        if (command.startsWith("mark ")) {
            int idx = parseIndex(command.substring(5)); // after "mark "
            try {
                Task t = taskList.mark(idx);

                if (!saveOrShowError(ui, storage, taskList.getInternalArray(), taskList.size())) {
                    return ui.endCapture();
                }

                ui.showMessage("Nice! I've marked this task as done:\n  " + t);
            } catch (IndexOutOfBoundsException e) {
                ui.showMessage("Invalid task number.");
            }
            return ui.endCapture();
        }

        if (command.startsWith("unmark ")) {
            int idx = parseIndex(command.substring(7)); // after "unmark "
            try {
                Task t = taskList.unmark(idx);

                if (!saveOrShowError(ui, storage, taskList.getInternalArray(), taskList.size())) {
                    return ui.endCapture();
                }

                ui.showMessage("OK, I've marked this task as not done yet:\n  " + t);
            } catch (IndexOutOfBoundsException e) {
                ui.showMessage("Invalid task number.");
            }
            return ui.endCapture();
        }

        if (command.startsWith("delete ")) {
            int idx = parseIndex(command.substring(7)); // after "delete "
            try {
                Task removed = taskList.delete(idx);

                if (!saveOrShowError(ui, storage, taskList.getInternalArray(), taskList.size())) {
                    return ui.endCapture();
                }

                ui.showMessage(
                        "Noted. I've removed this task:\n"
                                + "  " + removed + "\n"
                                + "Now you have " + taskList.size() + " tasks in the list."
                );
            } catch (IndexOutOfBoundsException e) {
                ui.showMessage("Invalid task number.");
            }
            return ui.endCapture();
        }

        if (command.startsWith("update ")) {
            String rest = input.substring(7).trim(); // after "update "

            if (rest.isEmpty()) {
                ui.showMessage("Please use: update <task number> <new description>");
                return ui.endCapture();
            }

            String[] parts = rest.split("\\s+", 2);
            if (parts.length < 2) {
                ui.showMessage("Please use: update <task number> <new description>");
                return ui.endCapture();
            }

            int idx = parseIndex(parts[0]);
            String newDesc = parts[1];

            try {
                Task t = taskList.update(idx, newDesc);

                if (!saveOrShowError(ui, storage, taskList.getInternalArray(), taskList.size())) {
                    return ui.endCapture();
                }

                ui.showMessage("Nice! I've updated this task:\n  " + t);
            } catch (IndexOutOfBoundsException e) {
                ui.showMessage("Invalid task number.");
            } catch (IllegalArgumentException e) {
                ui.showMessage(e.getMessage());
            }

            return ui.endCapture();
        }

        if (command.equals("todo") || command.startsWith("todo ")) {
            return handleTodoCommand(input, command);
        }

        if (command.equals("deadline") || command.startsWith("deadline ")) {
            return handleDeadlineCommand(input, command);
        }

        if (command.equals("event") || command.startsWith("event ")) {
            return handleEventCommand(input, command);
        }

        if (command.startsWith("find ")) {
            String keyword = command.substring(5).trim();
            try {
                ui.showMessage(taskList.formatFind(keyword));
            } catch (IllegalArgumentException e) {
                ui.showMessage(e.getMessage());
            }
            return ui.endCapture();
        }

        ui.showMessage("OOPS!!! I'm sorry, but I don't know what that means 😔");

        return ui.endCapture();
    }

    private String handleTodoCommand(String input, String command) {
        if (command.equals("todo")) {
            ui.showMessage(
                    "Want to add something to your task list? 📝\n"
                            + "Tell me what you need to do.\n"
                            + "Example: todo finish homework"
            );
            return ui.endCapture();
        }

        String taskDesc = input.substring(5).trim();
        if (taskDesc.isEmpty()) {
            ui.showMessage(
                    "Your todo description can’t be empty 🙂\n"
                            + "Try: todo finish homework"
            );
            return ui.endCapture();
        }

        try {
            Task newTask = taskList.add(new Todo(taskDesc));
            if (!save()) {
                return ui.endCapture();
            }

            ui.showMessage(
                    "Got it! I've added this task:\n"
                            + "  " + newTask + "\n"
                            + "Now you have " + taskList.size() + " tasks in the list."
            );
        } catch (IllegalStateException e) {
            ui.showMessage("Task list is full.");
        }

        return ui.endCapture();
    }

    private String handleDeadlineCommand(String input, String command) {
        if (command.equals("deadline")) {
            ui.showMessage(
                    "Got a deadline coming up? ⏰\n"
                            + "Tell me the task and when it's due.\n"
                            + "Example: deadline submit report /by 2026-03-10 1800"
            );
            return ui.endCapture();
        }

        String lower = input.toLowerCase();

        int byIndex = lower.indexOf(" /by ");
        boolean hasSlash = true;

        if (byIndex == -1) {
            byIndex = lower.indexOf(" by ");
            hasSlash = false;
        }

        if (byIndex == -1) {
            ui.showMessage(
                    "I need a due time for that 🙂\n"
                            + "Try: deadline <description> /by <YYYY-MM-DD HHmm>\n"
                            + "Example: deadline submit report /by 2026-03-10 1800"
            );
            return ui.endCapture();
        }

        String taskDesc = input.substring(9, byIndex).trim();
        String byRaw = input.substring(byIndex + (hasSlash ? 5 : 4)).trim();

        if (taskDesc.isEmpty()) {
            ui.showMessage(
                    "Your deadline description can’t be empty 🙂\n"
                            + "Example: deadline submit report /by 2026-03-10 1800"
            );
            return ui.endCapture();
        }

        if (byRaw.isEmpty()) {
            ui.showMessage(
                    "Please tell me *when* it’s due ⏰\n"
                            + "Example: deadline submit report /by 2026-03-10 1800"
            );
            return ui.endCapture();
        }

        if (taskList.isFull()) {
            ui.showMessage("Task list is full.");
            return ui.endCapture();
        }

        LocalDateTime dt = parseDateOrDateTime(ui, byRaw);
        if (dt == null) {
            return ui.endCapture();
        }

        Task newTask = byRaw.contains(" ")
                ? new Deadline(taskDesc, dt)
                : new Deadline(taskDesc, dt.toLocalDate());

        try {
            taskList.add(newTask);
            if (!save()) {
                return ui.endCapture();
            }

            ui.showMessage(
                    "Got it! I've added this task:\n"
                            + "  " + newTask + "\n"
                            + "Now you have " + taskList.size() + " tasks in the list."
            );
        } catch (IllegalStateException e) {
            ui.showMessage("Task list is full.");
        }

        return ui.endCapture();
    }

    private String handleEventCommand(String input, String command) {
        if (command.equals("event")) {
            ui.showMessage(
                    "Planning an event? 📅\n"
                            + "Tell me when it starts and ends.\n"
                            + "Example: event team meeting /from 2026-03-10 1800 /to 2026-03-10 1900"
            );
            return ui.endCapture();
        }

        String lower = input.toLowerCase();

        int fromIndex = lower.indexOf(" /from ");
        boolean fromSlash = true;
        if (fromIndex == -1) {
            fromIndex = lower.indexOf(" from ");
            fromSlash = false;
        }

        int toIndex = lower.indexOf(" /to ");
        boolean toSlash = true;
        if (toIndex == -1) {
            toIndex = lower.indexOf(" to ");
            toSlash = false;
        }

        if (fromIndex == -1 || toIndex == -1 || toIndex < fromIndex) {
            ui.showMessage(
                    "I need a start and end time 🙂\n"
                            + "Try: event <description> /from <start> /to <end>\n"
                            + "Example: event team meeting /from 2026-03-10 1800 /to 2026-03-10 1900"
            );
            return ui.endCapture();
        }

        String taskDesc = input.substring(6, fromIndex).trim();
        String fromRaw = input.substring(fromIndex + (fromSlash ? 7 : 6), toIndex).trim();
        String toRaw = input.substring(toIndex + (toSlash ? 5 : 4)).trim();

        if (taskDesc.isEmpty()) {
            ui.showMessage(
                    "Your event description can’t be empty 🙂\n"
                            + "Example: event team meeting /from 2026-03-10 1800 /to 2026-03-10 1900"
            );
            return ui.endCapture();
        }

        if (fromRaw.isEmpty() || toRaw.isEmpty()) {
            ui.showMessage(
                    "Please include both start and end times ⏰\n"
                            + "Example: event team meeting /from 2026-03-10 1800 /to 2026-03-10 1900"
            );
            return ui.endCapture();
        }

        if (taskList.isFull()) {
            ui.showMessage("Task list is full.");
            return ui.endCapture();
        }

        LocalDateTime start = parseDateOrDateTime(ui, fromRaw);
        if (start == null) {
            return ui.endCapture();
        }

        LocalDateTime end = parseDateOrDateTime(ui, toRaw);
        if (end == null) {
            return ui.endCapture();
        }

        if (!end.isAfter(start)) {
            ui.showMessage(
                    "Oops — the end time must be after the start time 🙂\n"
                            + "Example: event team meeting /from 2026-03-10 1800 /to 2026-03-10 1900"
            );
            return ui.endCapture();
        }

        Task newTask;
        try {
            newTask = new Event(taskDesc, start, end);
        } catch (IllegalArgumentException e) {
            ui.showMessage(
                    "OOPS! " + e.getMessage() + "\n"
                            + "Example: event team meeting /from 2026-03-10 1800 /to 2026-03-10 1900"
            );
            return ui.endCapture();
        }

        try {
            taskList.add(newTask);
            if (!save()) {
                return ui.endCapture();
            }

            ui.showMessage(
                    "Got it! I've added this task:\n"
                            + "  " + newTask + "\n"
                            + "Now you have " + taskList.size() + " tasks in the list."
            );
        } catch (IllegalStateException e) {
            ui.showMessage("Task list is full.");
        }

        return ui.endCapture();
    }

    /**
     * Parses a task index from user input.
     *
     * @param s String containing the index
     * @return Parsed integer index, or -1 if invalid
     */
    private static int parseIndex(String s) {
        try {
            return Integer.parseInt(s.trim());
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    /**
     * Parses either a date-time (yyyy-MM-dd HHmm) or a date (yyyy-MM-dd).
     * If only a date is provided, it is treated as start of day (00:00).
     * Shows an error message through the UI if the input is invalid.
     *
     * @param ui  User interface used to display error messages
     * @param raw Raw date/time input from the user
     * @return Parsed LocalDateTime, or {@code null} if the input is invalid
     */
    private static LocalDateTime parseDateOrDateTime(Ui ui, String raw) {
        try {
            return LocalDateTime.parse(raw, INPUT_DATETIME);
        } catch (DateTimeParseException ignoredDt) {
            try {
                LocalDate d = LocalDate.parse(raw, INPUT_DATE);
                return d.atStartOfDay();
            } catch (DateTimeParseException ignoredDate) {
                ui.showMessage("Please use: YYYY-MM-DD or YYYY-MM-DD HHmm (e.g. 2019-10-15 or 2019-10-15 1400)");
                return null;
            }
        }
    }

    /**
     * Saves the current tasks to storage.
     * If saving fails, shows an error message through the UI.
     *
     * @param ui      User interface used to display messages
     * @param storage Storage used to persist tasks
     * @param tasks   Array containing all stored tasks
     * @param count   Number of tasks currently in the list
     * @return {@code true} if saving succeeds, {@code false} otherwise
     */
    private static boolean saveOrShowError(Ui ui, Storage storage, Task[] tasks, int count) {
        try {
            storage.saveTasks(tasks, count);
            return true;
        } catch (IOException e) {
            ui.showMessage("Oops, I couldn't save your tasks to disk.");
            return false;
        }
    }

    private boolean save() {
        return saveOrShowError(ui, storage, taskList.getInternalArray(), taskList.size());
    }

}
